language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 2.7 on Linux"
      python: 2.7
      before_install:
        - pip install --upgrade pip
        - pip install pytest
      install: pip install .
      before_script:
        - cd corels/src/corels/src
        - make -B NGMP=1
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python -m pytest
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial          # required for Python >= 3.7
      before_install:
        - pip install --upgrade pip
        - pip install pytest
      install: pip install .
      before_script:
        - cd corels/src/corels/src
        - make -B NGMP=1
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python -m pytest
    - name: "Python 2.7 on Linux with GMP"
      python: 2.7
      before_install:
        - sudo apt-get install libgmp-dev
        - pip install --upgrade pip
        - pip install pytest
      install: pip install .
      before_script:
        - cd corels/src/corels/src
        - make -B
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python -m pytest
    - name: "Python 3.7 on Xenial Linux with GMP"
      python: 3.7
      dist: xenial          # required for Python >= 3.7
      before_install:
        - sudo apt-get install libgmp-dev
        - pip install --upgrade pip
        - pip install pytest
      install: pip install .
      before_script:
        - cd corels/src/corels/src
        - make -B
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python -m pytest
    - name: "Python 2.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip install --upgrade pip
        - pip install pytest
      install: pip install .
      before_script:
        - cd corels/src/corels/src
        - make -B NGMP=1
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python -m pytest
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install --upgrade pip
        - pip3 install pytest
      install: pip3 install .
      before_script:
        - cd corels/src/corels/src
        - make -B NGMP=1
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python3 -m pytest
    - name: "Python 2.7 on macOS with GMP"
      os: osx
      osx_image: xcode10.2
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install gmp
        - pip install --upgrade pip
        - pip install pytest
      install: pip install .
      before_script:
        - cd corels/src/corels/src
        - make -B
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python -m pytest
    - name: "Python 3.7 on macOS with GMP"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install gmp
        - pip3 install --upgrade pip
        - pip3 install pytest
      install: pip3 install .
      before_script:
        - cd corels/src/corels/src
        - make -B
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python3 -m pytest
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install: pip3 install pytest .
      before_script:
        - cd corels/src/corels/src
        - make -B NGMP=1
        - ./corels -b ../data/compas_test.out ../data/compas_test.label
      script: cd tests && python -m pytest
    - name: "Python 3.7 Docs on Xenial Linux"
      python: 3.7
      dist: xenial          # required for Python >= 3.7
      install:
        - pip install --upgrade pip
        - pip install sphinx
      script: cd docs && make html
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
